# Generated by Django 5.1.2 on 2024-11-03 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta Débito', 'Tarjeta Débito'), ('Transferencia', 'Transferencia'), ('Tarjeta Crédito', 'Tarjeta Crédito')], max_length=20)),
                ('ultimos_4_digitos', models.CharField(blank=True, max_length=4, null=True)),
                ('nombre_titular', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntegranteFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('relacion', models.CharField(max_length=50)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='finanzas.familia')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_transaccion', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Pagado', 'Pagado'), ('Pendiente', 'Pendiente'), ('Cuotificado', 'Cuotificado')], max_length=20)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='finanzas.categoria')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='finanzas.familia')),
                ('integrante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='finanzas.integrantefamilia')),
                ('metodo_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.metodopago')),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_por_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_cuotas', models.IntegerField()),
                ('cuotas_restantes', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='finanzas.transaccion')),
            ],
        ),
    ]
