# Generated by Django 5.1.2 on 2024-11-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='descripcion',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
