# Generated by Django 5.1.2 on 2024-11-05 02:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_transaccion_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='fecha_aplicacion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha_transaccion',
            field=models.DateField(),
        ),
    ]
