# Generated by Django 5.1.2 on 2024-11-06 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_transaccion_fecha_aplicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='familia',
        ),
    ]
